### ISSUE TITLE
Passwords Expiring

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#71]
Checking the default domain passwordsettings show passwords are expiring: 

```
samba-tool domain passwordsettings show
Password informations for domain 'DC=schule,DC=muster'

Password complexity: on
Store plaintext passwords: off
Password history length: 24
Minimum password length: 7
Minimum password age (days): 1
Maximum password age (days): 42
Account lockout duration (mins): 30
Account lockout threshold (attempts): 0
Reset account lockout after (mins): 30
```

This can be fixed by the command:
```
samba-tool domain passwordsettings set --history-length=0
samba-tool domain passwordsettings set --max-pwd-age=0
```

which should be the default.

In addition, is someone wants to configure password expiring,  we should set the expiry attribute of administrators and bindusers to  noexpiry to prevend these special users from expiring.

In samba tool this is done by:

`samba-tool user setexpiry Administrator --noexpiry `

**Comment by jeffbeck** [comment]
When creating an computer account we use the following attribute to let password expire only in the long long future:

      accountExpires => '9223372036854775807', # means never

(This is 2^63-1 if you are curious).

I guess it is  better to leave the samba default untouched. So only the sophomorix user have this setting.

**Comment by HappyBasher** [comment]
> In addition, is someone wants to configure password expiring, we should set the expiry attribute of administrators and bindusers to noexpiry to prevend these special users from expiring.

This is already done by setup.

**Comment by PLanB2008** [comment]
> When creating an computer account we use the following attribute to let password expire only in the long long future:

Is this used at all user creations? 

> This is already done by setup.

Which is probably true for the administrator and global-binduser account. This does not include new created bindusers by eg.

`
sophomorix-admin --create-global-binduser 
`

**Comment by jeffbeck** [comment]
I checked for adding students and teachers:
accountExpires is set to '9223372036854775807'.
This should mean that the account does expire in a very  very long time. 

I dont know why this isn't working???

`samba-tool user setexpiry Administrator --noexpiry
`
sets the following attributes:
userAccountControl 66050 or 66048
accountExpires: 0

Further research is needed

**Comment by PLanB2008** [comment]
> Further research is needed

Indeed. 
I just wanted to confirm my point and figured out, in another installation everything works like expected. 

Sadly I did not look into the user details before fixing it using the commands in the beginning.

I'll keep an eye on this, maybe this does only occur in special instances...

**Comment by PLanB2008** [comment]
Okay, got a user who seems to have an expired password. 

In which format is die pwdLastSet value provided? This does not seem to be a unix timestamp.
EDIT: Okay, I managed to figure this out by myself. According to https://www.epochconverter.com/ldap this translates to:
Epoch/Unix time: 1551880862
GMT: Wednesday, 6. March 2019 14:01:02

I still have to double check if this users password is not reset recently but this is how the user object looks like:

```
dn: CN=brucebanner,OU=j2z,OU=Students,OU=default-school,OU=SCHOOLS,DC=linuxmuster,DC=lan
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: user
cn: brucebanner
sn: Banner
givenName: Pascal
instanceType: 4
whenCreated: 20190306140102.0Z
displayName: Bruce Banner
uSNCreated: 9148
name: brucebanner
objectGUID: 8612d165-0984-4def-90e3-4f9186b51c72
userAccountControl: 512
badPwdCount: 0
codePage: 0
countryCode: 0
homeDirectory: \\linuxmuster.lan\default-school\students\j2z\brucebanner
homeDrive: H:
badPasswordTime: 0
badPasswordTime: 0
lastLogoff: 0
pwdLastSet: 131963544625526810
primaryGroupID: 513
objectSid: S-1-5-21-1186569087-607485451-749513746-1769
accountExpires: 9223372036854775807
sAMAccountName: brucebanner
sAMAccountType: 805306368
userPrincipalName: brucebanner@linuxmuster.lan
objectCategory: CN=Person,CN=Schema,CN=Configuration,DC=linuxmuster,DC=lan
unixHomeDirectory: /srv/samba/schools/default-school/students/j2z/holzwarthpas
 cal
sophomorixUnid: ---
sophomorixQuota: linuxmuster-global:---:---:new:---:
sophomorixQuota: default-school:---:---:new:---:
sophomorixMailQuota: ---:---:
sophomorixStatus: U
sophomorixCreationDate: 20190306132906.0Z
sophomorixTolerationDate: 19700101000000.0Z
sophomorixDeactivationDate: 19700101000000.0Z
sophomorixAdminClass: j2z
sophomorixExitAdminClass: unknown
sophomorixFirstPassword: D&vpm9HA3212
sophomorixFirstnameASCII: Bruce
sophomorixSurnameASCII: Banner
sophomorixBirthdate: 09.09.2001
sophomorixRole: student
sophomorixSchoolPrefix: ---
sophomorixSchoolname: default-school
sophomorixAdminFile: students.csv
sophomorixUserToken: ---
sophomorixComment: created by sophomorix
sophomorixWebuiDashboard: ---
sophomorixExamMode: ---
sophomorixWebuiPermissionsCalculated: sidebar:view:/view/dashboard: false
sophomorixWebuiPermissionsCalculated: sidebar:view:/view/lmn/landingpage: true
sophomorixMailQuotaCalculated: 1
sophomorixFirstnameInitial: B.
sophomorixSurnameInitial: B.
sophomorixCloudQuotaCalculated: ---
memberOf: CN=j2z,OU=j2z,OU=Students,OU=default-school,OU=SCHOOLS,DC=linuxmuste
 r,DC=lan
memberOf: CN=internet,OU=Management,OU=default-school,OU=SCHOOLS,DC=linuxmuste
 r,DC=lan
memberOf: CN=wifi,OU=Management,OU=default-school,OU=SCHOOLS,DC=linuxmuster,DC
 =lan
memberOf: CN=webfilter,OU=Management,OU=default-school,OU=SCHOOLS,DC=linuxmust
 er,DC=lan
memberOf: CN=intranet,OU=Management,OU=default-school,OU=SCHOOLS,DC=linuxmuste
 r,DC=lan
memberOf: CN=printing,OU=Management,OU=default-school,OU=SCHOOLS,DC=linuxmuste
 r,DC=lan
mail: brucebanner@mail.linuxmuster.net
lastLogonTimestamp: 132023787855526020
whenChanged: 20190515072625.0Z
uSNChanged: 24353
lastLogon: 132023787883011540
logonCount: 2
distinguishedName: CN=brucebanner,OU=j2z,OU=Students,OU=default-school,OU=
 SCHOOLS,DC=linuxmuster,DC=lan
```

**Comment by PLanB2008** [comment]
Okay after some more research we ran into this problem again.

We created a binduser, in this case called nextcloud-binduser.

This user has, like expected, a accountExpires attribute in the future
accountExpires: 9223372036854775807
which translates to GMT: Saturday, October 9, 4523 9:52:48 PM

Trying to run a ldapbearch using this user we run into this problem:

```
root@nextcloud:/var/www/nextcloud/data# ldapsearch -x -D 'CN=nextcloud-binduser,OU=Management,OU=default-school,OU=SCHOOLS,DC=linuxmuster,DC=lan' -W -H ldap://10.0.0.1:389 -b OU=SCHOOLS,DC=linuxmuster,DC=lan sAMAccountName=netzint-teacher
Enter LDAP Password:
ldap_bind: Invalid credentials (49)
        additional info: 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1
```

```
dn: CN=nextcloud-binduser,OU=Management,OU=default-school,OU=SCHOOLS,DC=linuxmuster,DC=lan
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: user
cn: nextcloud-binduser
sn: Binduser
givenName: default-school
instanceType: 4
whenCreated: 20190405145500.0Z
displayName: default-school Binduser
uSNCreated: 4162
name: nextcloud-binduser
objectGUID: 73e7616e-bfa7-4ad8-8553-d38bf6da05ac
userAccountControl: 512
badPwdCount: 0
codePage: 0
countryCode: 0
homeDirectory: \\linuxmuster.lan\default-school\management\nextcloud-binduser
homeDrive: H:
badPasswordTime: 0
lastLogoff: 0
lastLogon: 0
pwdLastSet: 131989497006654370
primaryGroupID: 513
objectSid: S-1-5-21-1877065124-740022452-3009792912-1140
accountExpires: 9223372036854775807
logonCount: 0
sAMAccountName: nextcloud-binduser
sAMAccountType: 805306368
userPrincipalName: nextcloud-binduser@linuxmuster.lan
objectCategory: CN=Person,CN=Schema,CN=Configuration,DC=linuxmuster,DC=lan
mail: nextcloud-binduser@linuxmuster.lan
unixHomeDirectory: /srv/samba/schools/default-school/management/nextcloud-bind
 user
sophomorixUnid: ---
sophomorixQuota: linuxmuster-global:---:---:new:---:
sophomorixQuota: default-school:---:---:new:---:
sophomorixMailQuota: ---:---:
sophomorixStatus: P
sophomorixCreationDate: 20190405145455.0Z
sophomorixTolerationDate: 19700101000000.0Z
sophomorixDeactivationDate: 19700101000000.0Z
sophomorixAdminClass: s_default-school
sophomorixExitAdminClass: unknown
sophomorixFirstPassword: ---
sophomorixFirstnameASCII: default-school
sophomorixSurnameASCII: Binduser
sophomorixBirthdate: ---
sophomorixRole: schoolbinduser
sophomorixSchoolPrefix: ---
sophomorixSchoolname: default-school
sophomorixAdminFile: none
sophomorixUserToken: ---
sophomorixComment: created by sophomorix
sophomorixWebuiDashboard: ---
sophomorixExamMode: ---
sophomorixMailQuotaCalculated: 1
sophomorixFirstnameInitial: d.-s.
sophomorixSurnameInitial: B.
sophomorixCloudQuotaCalculated: ---
memberOf: CN=s_default-school,OU=default-school,OU=SCHOOLS,DC=linuxmuster,DC=l
 an
lastLogonTimestamp: 132020694019968350
whenChanged: 20190511173001.0Z
uSNChanged: 14373
distinguishedName: CN=nextcloud-binduser,OU=Management,OU=default-school,OU=SC
 HOOLS,DC=linuxmuster,DC=lan
```

So I assume there's more than the accountExpires date.  I assume, we have to set this:

`samba-tool domain passwordsettings set --max-pwd-age=0`

because the controller looks into the created date and calculates if the max-pwd-age is above this limit. If so, the user will be disabled.

But this is just an assumption... 

Default settings right now:

root@server:/usr/lib/cups/filter# samba-tool domain passwordsettings show
Global parameter ntlm auth found in service section!
Password informations for domain 'DC=linuxmuster,DC=lan'

```
Password complexity: on
Store plaintext passwords: off
Password history length: 24
Minimum password length: 7
Minimum password age (days): 1
Maximum password age (days): 42
Account lockout duration (mins): 30
Account lockout threshold (attempts): 0
Reset account lockout after (mins): 30
```

**Comment by maximwolf** [comment]
**Default by setup**

pdbedit -u global-binduser -v

Unix username:        global-binduser
NT username:
Account Flags:        [UX         ]
User SID:             S-1-5-21-1877065124-740022452-3009792912-1128
Primary Group SID:    S-1-5-21-1877065124-740022452-3009792912-513
Full Name:            Global Binduser
Home Directory:       \\linuxmuster.lan\linuxmuster-global\management\global-binduser
HomeDir Drive:        H:
Logon Script:
Profile Path:
Domain:
Account desc:
Workstations:
Munged dial:
Logon time:           0
Logoff time:          0
Kickoff time:         0
Password last set:    Di, 02 Apr 2019 09:30:44 UTC
Password can change:  Di, 02 Apr 2019 09:30:44 UTC
Password must change: Di, 19 Jan 2038 03:14:07 UTC
Last bad password   : 0
Bad password count  : 0
Logon hours         : FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

**Edited User** with:  samba-tool user setexpiry nextcloud-binduser --noexpiry

pdbedit -u nextcloud-binduser -v

Unix username:        nextcloud-binduser
NT username:
Account Flags:        [UX         ]
User SID:             S-1-5-21-1877065124-740022452-3009792912-1140
Primary Group SID:    S-1-5-21-1877065124-740022452-3009792912-513
Full Name:            default-school Binduser
Home Directory:       \\linuxmuster.lan\default-school\management\nextcloud-binduser
HomeDir Drive:        H:
Logon Script:
Profile Path:
Domain:
Account desc:
Workstations:
Munged dial:
Logon time:           0
Logoff time:          0
Kickoff time:         0
Password last set:    Mo, 20 Mai 2019 08:28:36 UTC
Password can change:  Mo, 20 Mai 2019 08:28:36 UTC
Password must change: Di, 19 Jan 2038 03:14:07 UTC
Last bad password   : 0
Bad password count  : 0
Logon hours         : FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF


**Created User**

pdbedit -u unifi-binduser -v

Unix username:        unifi-binduser
NT username:
Account Flags:        [U          ]
User SID:             S-1-5-21-1877065124-740022452-3009792912-2051
Primary Group SID:    S-1-5-21-1877065124-740022452-3009792912-513
Full Name:            default-school Binduser
Home Directory:       \\linuxmuster.lan\default-school\management\unifi-binduser
HomeDir Drive:        H:
Logon Script:
Profile Path:
Domain:
Account desc:
Workstations:
Munged dial:
Logon time:           0
Logoff time:          0
Kickoff time:         Do, 14 Sep 30828 02:48:05 UTC
Password last set:    Do, 11 Apr 2019 08:48:54 UTC
Password can change:  Do, 11 Apr 2019 08:48:54 UTC
Password must change: never
Last bad password   : 0
Bad password count  : 0
Logon hours         : FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

**Comment by jeffbeck** [comment]
This is fixed in 3.69.1-1 the following way:

1) All sophomorix users are created with userAccountControl 66048 (enabled,noexpity).
If they are disabled userAccountControl is wwitched to 66050 (the relevant bit is changed).

2) For existing users:

run 

`sophomorix-passwd --set-password-noexpiry-all-sophomorix-users`

To make the existing accounts permanent.

I added a tool to show the password expiry date on the server:

`sophomorix-passwd --show-password-expiry-days kep42`

The password should be valid over 10.000.000 days (the end of a generously chosen counter)


**Please verify with windows-clients, linux-clients, ...  if that works.**

**Comment by PLanB2008** [comment]
> 
> I added a tool to show the password expiry date on the server:
> 
> `sophomorix-passwd --show-password-expiry-days kep42`
> 

This command does not seem to work, 


```
root@server:/etc/linuxmuster/sophomorix/default-school# sophomorix-passwd --show-password-expiry-days global-admin
Command line::
Hmmh. do not know what to do with option info
Option json is a modifier option
Option verbose is a modifier option
* forcing info mode
Option combinations successfully checked
OK: SophomorixSchemaVersion 1 matches required Version 1
#### Reading /usr/share/sophomorix/devel/sophomorix.ini                   ####
Distro-check: Ubuntu 18.04 is OK
#### Reading /etc/samba/smb.conf                                          ####
#### Reading /usr/lib/linuxmuster-webui/etc/default-ui-permissions.ini    ####
#### Parsing: net conf list                                               ####
#### Asking domain passwordsettings from samba                            ####
#### Reading /usr/share/sophomorix/devel/master/sophomorix.conf.master    ####
#### Reading /etc/linuxmuster/sophomorix/sophomorix.conf                  ####
#### OK: default-school share exists                                      ####
#### OK: /etc/linuxmuster/sophomorix/default-school/school.conf           ####
#### Reading /usr/share/sophomorix/devel/master/school.conf.master        ####
#### Reading /etc/linuxmuster/sophomorix/default-school/school.conf       ####
#### 0 ERRORS, 0 WARNINGS -> let's go                                     ####
#### /usr/sbin/sophomorix-passwd started ...                              ####

No result found: Does user "global-admin" exist?
```

I'm not sure if this works or not.

Using noexpiry keeps the 

`Password must change: Di, 19 Jan 2038 04:14:07 CET`

attribute, on other users it says never.


I'm still not really sure what this is all about.

**Comment by jeffbeck** [comment]
On my system the command works, if the user exists (even if its an admin)

The command only SHOWS how long passwords are valid

Idont understand the rest of you message is 'noexpiry' a tool or option or ...?

**Comment by jeffbeck** [comment]
Maybe I understand now:

You are using: pdbedit -u global-admin -v

which shows never as: Di, 19 Jan 2038 04:14:07 CET

since pdbedit is a really old tool I guess this is the end of unix epoch time problem:
https://de.wikipedia.org/wiki/Jahr-2038-Problem

**Comment by jolly-jump** [comment]
As I wrote in ASK: the command does not work for me either:
```
 sophomorix-passwd --show-password-expiry-days kuechel
Command line::
Option verbose is a modifier option
Option json is a modifier option
Hmmh. do not know what to do with option info
* forcing info mode
Option combinations successfully checked
OK: SophomorixSchemaVersion 1 matches required Version 1
#### Reading /usr/share/sophomorix/devel/sophomorix.ini                   ####
Distro-check: Ubuntu 18.04 is OK
#### Reading /etc/samba/smb.conf                                          ####
#### Reading /usr/lib/linuxmuster-webui/etc/default-ui-permissions.ini    ####
#### Parsing: net conf list                                               ####
#### Asking domain passwordsettings from samba                            ####
#### Reading /usr/share/sophomorix/devel/master/sophomorix.conf.master    ####
#### Reading /etc/linuxmuster/sophomorix/sophomorix.conf                  ####
#### OK: default-school share exists                                      ####
#### OK: /etc/linuxmuster/sophomorix/default-school/school.conf           ####
#### Reading /usr/share/sophomorix/devel/master/school.conf.master        ####
#### Reading /etc/linuxmuster/sophomorix/default-school/school.conf       ####
#### 0 ERRORS, 0 WARNINGS -> let's go                                     ####
#### /usr/sbin/sophomorix-passwd started ...                              ####

No result found: Does user "kuechel" exist?
```

**Comment by jeffbeck** [comment]
This should be fixed long time ago
